### ISSUE TITLE
Conflicting uploads fight for upload bar.

### ISSUE THREAD

**Issue by HumbleDeer** [turlando/airhead#22]
https://youtu.be/qIGEdIvn1X0

**Comment by edne** [comment]
Hi, here the front-end guy. I'm working on a fix, in the meanwhile can you please re-open this issue [here](https://github.com/edne/airhead-frontend)?

**Comment by turlando** [comment]
Discussion moved to [airhead-frontend#18](https://github.com/edne/airhead-frontend/issues/18).
